name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Verify Firebase CLI Installation
      run: firebase --version

    - name: Authenticate with Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "$FIREBASE_SERVICE_ACCOUNT" > firebase-service-account.json
        firebase auth:import --account-key firebase-service-account.json

    - name: Deploy to Firebase
      run: firebase deploy --only hosting
